web:
  restart: always
  build: ./web
  expose:
    - "8000"
    - "8001"
  environment:
    - DEBUG=True
    - DEV=True
    - DATABASE_URL=postgres://postgres:@postgres:5432/postgres
    - SECRET_KEY=notasecretreplaceme
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web/alkemata/alkemata:/usr/src/app
  command:  python manage.py runserver 0.0.0.0:8000
#  command: /usr/local/bin/gunicorn alkemata.wsgi:application -w 2 -b :8000 --reload

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web
   

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /mnt/vdb/database:/var/lib/postgresql/data
  ports:
    - "5432:5432"

jupyter:
  image: jupyter/scipy-notebook:latest
  ports:
    - "8888:8888"
  volumes:
    - ./kernelClient:/home/jovyan/notebooks
  command: jupyter kernelgateway --KernelGatewayApp.ip=0.0.0.0 --KernelGatewayApp.port=8888

redis:
  image: redis:3.0-alpine

npm:
  build: ./npm/
  volumes:
    - ./web/alkemata/alkemata/client:/usr/src/app 
