# Generated by Django 2.0.8 on 2018-09-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180906_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='typeArticle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ArticleType'),
        ),
    ]
