# Generated by Django 2.0.8 on 2018-08-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='connected_kernels',
            field=models.ManyToManyField(related_name='connected_kernels', to='chat.Kernel'),
        ),
    ]
